setup.cfg, src/ai/backend/common/types.py, tests/test_types.py
ImageRef class generate_aliases, merge_aliases methods implemented
both methods return types changed:
`Mapping[str, str]` ====> `Mapping[str, ImageRef]`
`Sequence[str]` =====> `Mapping[str, ImageRef]`
=> generate_aliases , merge_aliases in ImageRef class implemented

setup.cfg, src/ai/backend/common/docker.py, src/ai/backend/common/etcd.py, tests/conftest.py, tests/test_etcd.py, tests/test_types.py
Now we want to set global (cluster-level) configs, scaling-group configs, and per-node configs separately and merge them when reading configurations.
Let the manager and the agent provide actual scope prefixes (e.g., per-node prefix requires instance IDs) and the AsyncEtcd instance use them.
=> Scoped configurations on etcd

src/ai/backend/common/types.py
This PR is a part of lablup/backend.ai-manager#206 and lablup/backend.ai-agent#155, which adds a `mount_map` parameter to `KernelCreationConfig`.
=> Add mount_map to type KernelCreationConfig

src/ai/backend/common/etcd.py, src/ai/backend/common/types.py, tests/conftest.py, tests/test_etcd.py
* Automatically unquote nested dict keys from `etcd.get_prefix()` to avoid caller mistakes.
* Add a new method `etcd.put_prefix()` which automatically quotes the given nested dict keys as an analogy.
- Existing `etcd.put_dict()` method accepts only flattened dicts with already quoted keys.
- From now on, `etcd.put_prefix()` is the preferred method in new codes.
=> etcd: Automatically unquote dict keys for get-prefix operation

changes/37.feature, src/ai/backend/common/utils.py, tests/test_utils.py
This PR introduces a function which convert humanized timedelta string into a Python's `timedelta` object.
For example,
```python
>>> str_to_timedelta('30min')
datetime.timedelta(seconds=1800)
>>> str_to_timedelta('1d1hr')
datetime.timedelta(days=1, seconds=3600)
>>> str_to_timedelta('2hours 15min')
datetime.timedelta(seconds=8100)
>>> str_to_timedelta('20sec')
datetime.timedelta(seconds=20)
>>> str_to_timedelta('300')
datetime.timedelta(seconds=300)
>>> str_to_timedelta('-1day')
datetime.timedelta(days=-1)
```
Related: lablup/backend.ai#130, OP#101
=> feat: add function to convert humanized timedelta str t timedelta obj

src/ai/backend/common/plugin/monitor.py
- Change default value from {} to None.
- Fix of an error not caught in the previous PR.
=> Fix error monitor plugin default value to None

changes/52.feature, src/ai/backend/common/service_ports.py
Since parsing service port modules are used in both manager and agent, service port is refactored into backend.ai-common
=> Service port module

changes/63.feature, src/ai/backend/common/types.py
This is for MIG support with the brand new NVIDIA DGX-A100 nodes.
The unique resource slot only allows the unique assignment of a single resource "1.0" to individual container.
=> Add support for unique resource slots

changes/91.fix, tests/redis/conftest.py
=> test: Stabilize tests using a single redis container as fixture

changes/99.feature, src/ai/backend/common/validators.py, tests/test_validators.py
Related PR comment : https://github.com/lablup/backend.ai-manager/pull/498#discussion_r756821898
This will support months and years arguments in TimeDuration class.
* `ai.backend.common.validators.TimeDuration` now support second, weeks, days, hours, minutes arguments.
* "clear_history" function for `mgr clear-history` cli command receives data retention limit as an argument(e.g., 20d, 1mo, 6mo, 1yr') and calculates the expiration date using TimeDuration class.
```
from ai.backend.common.validators import TimeDuration
duration = TimeDuration()
expiration_date = today - duration.check_and_return(retention)
```
* When argument is a value such as "1yr" or "6mo", the function can't calculate using TimeDuration.
=> feat: Update TimeDuration to support years and months

changes/104.fix, setup.cfg, src/ai/backend/common/cli.py, src/ai/backend/common/types.py
- setup: Upgrade mypy to 0.920
- fix: Remove bogus type-casting
- fix: Call `__init__()` as a classmethod
=> fix: Apply mypy 0.920 update

changes/105.fix, setup.cfg, src/ai/backend/common/etcd.py, src/ai/backend/common/utils.py, tests/test_utils.py
This PR updates mypy to 0.930.
=> Update mypy to 0.930

changes/112.fix.md, src/ai/backend/common/events.py, tests/conftest.py, tests/redis/conftest.py, tests/test_events.py
* Allow users to customize consumer/subscriber exception handlers
when creating `EventDispatcher` objects.
* Directly call synchronous event handlers instead of using `loop.call_soon()`
to take advantage of the underlying exception handling mechanism of
`PersistentTaskGroup`.
=> fix: Import and update `EventDispatcher` test cases from the manager

changes/113.misc.md, src/ai/backend/common/types.py, tests/redis/test_pipeline.py
This does not add any new feature or fix bugs, but exemplify how to use Redis pipelines with our `RedisConnectinInfo` connection wrapper and the `redis.execute()` helper function.
=> feat: Add a Redis pipeline test case as an example

changes/115.fix.md, src/ai/backend/common/redis.py
resolves lablup/backend.ai#355
* If pipelines are used, the error code may not come in the beginning of
`e.args[0]` but later in the message due to wrapping of underlying
exceptions in aioredis.
e.g., "Command # 1 (SET xyz 123) of pipeline caused error: ('NOREPLICAS Not enough good replicas to write.',)"
=> fix: Generalize error message pattern matching for pipelines

.github/workflows/default.yml, .github/workflows/timeline-check.yml, changes/123.breaking.md, setup.cfg, src/ai/backend/common/argparse.py, src/ai/backend/common/etcd.py, src/ai/backend/common/validators.py
=> setup: Set the minimum required Python version to 3.10

changes/126.fix.md, src/ai/backend/common/redis.py
- fix: typing of redis.execute_script()
- fix: make it more precise
=> fix: Argument typing of `redis.execute_script()`

changes/128.feature.md, src/ai/backend/common/validators.py, tests/test_validators.py
We can just pass int or float directly to `timedelta` and it will automatically normalize them as days, seconds, and microseconds.
=> feat: Accept numbers as well in validators.TimeDuration

changes/127.misc, src/ai/backend/common/docker.py, tests/test_docker.py
This PR removes old codes in `ImageRef` class, which was used to perform Etcd operations when we used Etcd as our image metadata storage.
=> refactor: remove unused codes in `ImageRef` class

changes/139.fix, src/ai/backend/common/redis.py
Given an incorrect redis url, there occurs an `aioredis.exceptions.ConnectionError` when trying to run a command with it. Therefore, I made some changes to fix two problems.
1. ([backend.ai-manager](https://github.com/lablup/backend.ai-manager)) Added a coroutine function, `ai.backend.common.redis.pool_redis_connection`, to check redis connection explicitly. This runs `aioredis.client.Redis.time()` to test if connection is built and raises a `aioredis.exceptions.ConnectionError` with printing additional error message when unable to connect to redis server.
2. ([backend.ai-agent](https://github.com/lablup/backend.ai-agent)) I found that there happens an infinite loop in `ai.backend.common.redis.execute` when unable to connect to redis server, especially with incorrect url which has no …
=> fix: Add error logs to notify ConnectionError caused by incorrect redis url
