src/ai/backend/common/types.py

* Make ResourceSlot be aware of infinity values.
* Refactor its methods to be more specific to the use-cases, instead of offering complex combinations of behavioral options.
* Reduce and constrain the cases that requires "known resource slot types". For instance, `to_json()`, `from_json()` methods should just work without them. To achieve this, we keep the internal representation to have only Decimal (or int) values.

Refactor ResourceSlot

---

src/ai/backend/common/exception.py
src/ai/backend/common/types.py

Supports lablup/backend.ai-agent#153 (→ lablup/backend.ai-agent#154) and lablup/backend.ai-console#157.

Support typing for auto-pull related changes

---

requirements-ci.txt
requirements-dev.txt
src/ai/backend/common/logging.py
src/ai/backend/common/plugin.py
src/ai/backend/common/types.py
tests/test_docker.py
tests/test_identity.py
tests/test_types.py

Unified resource slots

---

.github/workflows/flake8-matcher.json
.github/workflows/lint-flake8.yml
.github/workflows/mypy-matcher.json
.github/workflows/typecheck-mypy.yml
src/ai/backend/common/argparse.py

Let's utilize [problem matchers](https://github.com/actions/toolkit/blob/master/docs/problem-matchers.md).

Improve CI using inline annotations for lint/typecheck errors

---

setup.cfg
src/ai/backend/common/logging.py
tests/test_logging.py

We need to provide fallback routines when pickling and unpickling fails.

Handle pickle and unpickle errors for logging properly

---

src/ai/backend/common/utils.py
tests/test_utils.py

To support lablup/backend.ai-manager#236, it adds a new `get_random_seq()` utility function.

Improve scheduling tick

---

src/ai/backend/common/validators.py
tests/test_validators.py

This PR adds new type definitions for lablup/backend.ai-manager#235.
Ticket: OP#162

Implement new types for error logging

---

src/ai/backend/common/logging.py
src/ai/backend/common/validators.py
tests/test_validators.py

Add an explicit monkey-patcher function to be called at startup.
resolves lablup/backend.ai#158

Monkeypatch for trafaret.DataError pickling support

---

src/ai/backend/common/config.py
src/ai/backend/common/validators.py

Let's move reusable config IVs to the commons.

Refactor configs

---

changes/47.feature
changes/47.fix
src/ai/backend/common/plugin/__init__.py
src/ai/backend/common/plugin/monitor.py
tests/test_plugin.py

Update plugin and plugin context methods.
Tracking PR lablup/backend.ai-manager#316

fix: regression of error logs API

---

changes/48.feature
codecov.yml
src/ai/backend/common/identity.py
src/ai/backend/common/types.py

This is the common's part of lablup/backend.ai#217

Basic multi-container session

---

changes/71.fix
src/ai/backend/common/validators.py

fix: Update for PyJWT 2.0

---

.github/workflows/timeline-check.yml
changes/76.feature
src/ai/backend/common/events.py

Internal ticket: OP#1157
refs lablup/backend.ai-manager#415

Update for the new v3 scheduler

---

changes/80.fix
setup.cfg
src/ai/backend/common/asyncio.py
src/ai/backend/common/files.py
src/ai/backend/common/identity.py
src/ai/backend/common/networking.py
src/ai/backend/common/utils.py
tests/test_utils.py

refactor: Add more type annotation to the utils module

fix: Support batch-type session refactoring

---

changes/96.fix
src/ai/backend/common/redis.py

* Make it similar to Redis' internal calculation based on the keep-idle
value.

fix: Adjust redis keepalive opts

---

changes/98.feature
src/ai/backend/common/lock.py

This resolves lablup/backend.ai#312.

Migrate file-based lock code from storage-proxy package

---

changes/110.fix.md
src/ai/backend/common/redis.py

* This prevents xautoclaim-ing messages that has long processing time.

fix: Improve EventDispatcher stability

---

changes/118.feature
src/ai/backend/common/cli.py
src/ai/backend/common/config.py
src/ai/backend/common/docker.py
src/ai/backend/common/types.py
tests/test_docker.py

This PR adds new `architecture` variable on `ImageRef` class to distinguish image architecture. This PR resolves lablup/backend.ai#374.

feature: add `architecture` variable on `ImageRef`

---

changes/122.feature.md
src/ai/backend/common/types.py

A follow-up to #121
* These may be useful for searching/analyzing vfolder mounts

feat: Add more fields to VFolderMount

---

changes/129.feature.md
src/ai/backend/common/distributed.py
src/ai/backend/common/lock.py
tests/test_distributed.py

- refactor: Use abstract lock interface
- refactor: Make FileLock a AbstractDistributedLock
- test: Migrate and update the test case

refactor: Migrate `distributed` module to common pkg

---

changes/135.fix.md
setup.cfg
src/ai/backend/common/bgtask.py

Migrate bgtask framework to common
